server:
  port: 8001
# 日志
logging:
  config: classpath:logback.xml
#dubbo配置
dubbo:
  # 应用部分
  application:
    name: dubbo-consumer
#    service-discovery:
#      migration: FORCE_APPLICATION
  # 注册部分
  registry:
    address: zookeeper://127.0.0.1:2181
